//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etudiant.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPDataBaseEntities : DbContext
    {
        public TPDataBaseEntities()
            : base("name=TPDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<Etudiants> Etudiants { get; set; }
        public virtual DbSet<EtudiantsCours> EtudiantsCours { get; set; }
        public virtual DbSet<Examens> Examens { get; set; }
        public virtual DbSet<ExamensCoursEtudiants> ExamensCoursEtudiants { get; set; }
        public virtual DbSet<Professeurs> Professeurs { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
    }
}
