//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etudiant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string MotDePasse { get; set; }
        public string Mail { get; set; }
        public string Profil { get; set; }
        public string Etat { get; set; }
        public Nullable<int> FK_Professeurs { get; set; }
        public Nullable<int> FK_Etudiants { get; set; }
    
        public virtual Etudiants Etudiants { get; set; }
        public virtual Professeurs Professeurs { get; set; }
    }
}
